### ISSUE TITLE
Poder extraer de un .txt la lista

### ISSUE THREAD

**Issue by Sweetdreamstome** [Sweetdreamstome/experimentos_kg#15]

**Comment by Sweetdreamstome** [comment]
Puedo extraer el texto de un archivo .txt, pero este archivo debe ser super sencillo y cada texto dentro de un popup debe tener como separación un "\n" dentro del .txt para que funcione... no sé si esto es hardcoding o está bien :( @mgutierrezc espero al viernes para hacer el code review?

**Comment by mgutierrezc** [comment]
No prob. Podemos chequearlo ahora. En lugar de un txt, pon el texto del pop up como un `.html`. Al html, añádele los tags que consideres necesarios y úsalos como separación
