### ISSUE TITLE
Cambiar de nombre al repo 

### ISSUE THREAD

**Issue by mgutierrezc** [Sweetdreamstome/experimentos_kg#17]
Acabo de notar que el código de pop ups y del exp están en el mismo repo. Hay que mover lo de pop ups a un repo separado y transferir los issues de pop ups a ese nuevo repo para no perder lo comentado allí:

https://docs.github.com/en/issues/tracking-your-work-with-issues/managing-issues/transferring-an-issue-to-another-repository

**Comment by mgutierrezc** [comment]
Espera, creo que me he confundido. Este repo es solo del pop up? Si es así, ignora lo anterior y solo cambiale de nombre para indicar eso plis

**Comment by mgutierrezc** [comment]
Cuando lo hagas, cierra este issue

**Comment by Sweetdreamstome** [comment]
Ya cambié el nombre y eliminé las carpetas innecesarias. Graciasss:)
